### ISSUE TITLE
Can I upload Videos as well?

### ISSUE THREAD

**Issue by rdcoder33** [shellbear/imgur.dart#3]
Thanks for this amazing plugin!
Example only shows how to upload images but imgur also accepts videos.

Can I upload videos using this plugin?
If not can you please add that feature as well.

Thanks again.

**Comment by shellbear** [comment]
Hello!

Yes there is a `uploadVideo` method that should do what you need!

https://pub.dev/documentation/imgur/latest/imgur/ImageService/uploadVideo.html
